### ISSUE TITLE
[contact] TOSHIBA Satellite Pro 6100 Recovery CD-ROM

### ISSUE THREAD

**Issue by Ghost-chu** [NikNikovsky/Nik-Windows-XP#6]
Hi Nik Nikovsky, I saw on archive.org that you are looking for available TOSHIBA Satellite Pro 6100 Recovery CD-ROM disc images.
I found them from home earlier this year and exported a copy.
They are Chinese versions of the CD-ROMs, and I don't know if this will help you - I didn't find your e-mail address, so I decided to open an Issue directly under this item in the hope of reaching you.

![p2](https://github.com/NikNikovsky/Nik-Windows-XP/assets/30802565/83a3b66f-1181-4f87-ba13-ea81496b32a9)
![p1](https://github.com/NikNikovsky/Nik-Windows-XP/assets/30802565/95ede50f-77e0-422b-8ea1-660f2521b5a0)

They are GHO files, not regular USB boot ISOs.
You may need to check the BIOS to see if there is a corresponding recovery program, or try booting from a PE -- I haven't touched the device at all, but I do have them on CD.

https://drive.google.com/drive/folders/1OSXFOmdhHab-Y3pCfOr1MS1FF8RdmFj5?usp=sharing

Not sure if it will help you, but it would be great if it did.

You can upload it to Archive.org without my authorization and I'd be happy for it to be shared.

**Comment by NikNikovsky** [comment]
I have no idea how to burn GHO files, point me to special software please

**Comment by Ghost-chu** [comment]
> I have no idea how to burn GHO files, point me to special software please

You shouldn't burn the GHO file, but instead -- burn the whole ISO file into an CD (or USD stick, but I'm not sure if it working, CD is best), and follow the guide https://www.manualslib.com/manual/180369/Toshiba-6100.html?page=88#manual try to boot into recovery mode.

GHO is a hard-drive image, can be restore via Ghost software which included in ISO file.

**Comment by NikNikovsky** [comment]
I am going to tell you one thing btw:
1. The CD/DVD drive is pretty much dead.
2. I don't have any CDs/DVDs

**Comment by NikNikovsky** [comment]
(feel free to still make contact)

**Comment by Ghost-chu** [comment]
I don't actually have the device, but if you can think of a way to get the calc to run that GHOST.EXE file, good luck might be in order.

[Hold 'U' key while booting will lead BIOS startup from a USB drive.](https://www.manualslib.com/manual/180369/Toshiba-6100.html?page=150)

Then you can try burn the ISO into a USB drive and startup from it.

Or you can also try boot into an old PE and see if GHOST.EXE can be run from PE.

If you don't have a USB drive, seems this device also support NIC PXE boot, you can use [iVentoy](https://www.iventoy.com/) to setup a PXE server in LAN.

**Comment by NikNikovsky** [comment]
Did I mention that the laptop is in a state of disassembly that I for some reason can't undo?
Also, iVentoy doesn't work.
